export interface SentimentSegment {
  time: string;
  sentiment: string;
  text: string;
  speaker?: string;
}

export interface Meeting {
  id: string;
  title: string;
  summary: string;
  transcriptContent: string;
  status: string;
  wordCount?: number;
  date?: any;
  speakers?: string[]; // Kept optional as it's generated by the Swarm
  sentimentData?: {
    overall: number;
    segments?: SentimentSegment[];
  } | null;
}

export interface Decision {
  id: string;
  meetingId: string;
  text: string;
  category: string;
  authorId?: string;
}

export interface ActionItem {
  id: string;
  meetingId: string;
  responsible: string;
  task: string;
  dueDate: string;
  status: string;
  authorId?: string;
}

export interface MeetingRef {
  id: string;
  title: string;
}
