import React from 'react';
import { BookOpen, UploadCloud, BrainCircuit, Search, HelpCircle, CheckSquare } from 'lucide-react';
import { motion } from 'motion/react';

export const Help: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-10 pb-20">
      <section className="space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-2xl text-primary mb-4">
          <BookOpen className="w-8 h-8" />
        </div>
        <h1 className="text-4xl font-black text-primary font-headline tracking-tight">Documentation & Help</h1>
        <p className="text-xl text-on-surface-variant font-body">Learn how to maximize your editorial intelligence workflow and stop the double-work dilemma.</p>
      </section>

      <div className="grid grid-cols-1 gap-6 pt-6">
        <DocSection 
          icon={<UploadCloud />}
          num="01"
          title="Uploading Transcripts"
          content={
            <div className="space-y-4">
              <p>The Narrative is built to instantly ingest raw text outputs from your favorite meeting tools (Zoom, Google Meet, Teams, etc).</p>
              <ul className="list-disc pl-5 space-y-2 text-on-surface-variant">
                <li>Navigate to the <strong>Upload</strong> tab using the sidebar.</li>
                <li>Drag and drop your <code>.txt</code> or <code>.vtt</code> transcript files directly into the dropzone.</li>
                <li>You can add multiple speakers simply by ensuring their names prepend their dialogue lines in the text file.</li>
                <li>Once uploaded, the AI will begin processing the transcript in the background. You'll be notified via the bell icon when it's ready.</li>
              </ul>
            </div>
          }
        />

        <DocSection 
          icon={<BrainCircuit />}
          num="02"
          title="Meeting Intelligence"
          content={
            <div className="space-y-4">
              <p>Clicking on any meeting in your Dashboard opens the Intelligence view, your primary workspace for analyzing dialogue and narrative flows.</p>
              <ul className="list-disc pl-5 space-y-2 text-on-surface-variant">
                <li><strong>Sentiment Analysis:</strong> The visual graph maps the "vibe" of the meeting over time, allowing you to instantly spot moments of conflict or agreement without reading the transcript.</li>
                <li><strong>Speaker Alignment:</strong> See exactly which participants were acting cooperatively versus confrontationally.</li>
                <li><strong>Executive Synthesis:</strong> Read the automated executive summary of the conversation generated by the Lead Swarm Agent.</li>
                <li><strong>Contextual AI:</strong> Use the chat box at the bottom to query specific facts or pull context directly from that single meeting.</li>
              </ul>
            </div>
          }
        />

        <DocSection 
          icon={<CheckSquare />}
          num="03"
          title="The Workstream"
          content={
            <div className="space-y-4">
              <p>The Swarm extracts all strategic decisions and action items and funnels them centrally into your Master Workstream, acting as your automated project manager.</p>
              <ul className="list-disc pl-5 space-y-2 text-on-surface-variant">
                <li><strong>Global vs Local:</strong> View every single task assigned across the entire company, or use the top-right filter dropdown to isolate tasks to a specific meeting snippet.</li>
                <li><strong>Interactive Checkboxes:</strong> The Workstream is hooked directly into the real-time database! You can physically check the circle next to an action item to permanently complete it and strike it through.</li>
                <li><strong>Strategic Decisions:</strong> Review critical policy or directional choices made without digging through the weeds of the conversation.</li>
              </ul>
            </div>
          }
        />

        <DocSection 
          icon={<Search />}
          num="04"
          title="Global Inquiry Chat"
          content={
            <div className="space-y-4">
              <p>The global chat acts as a contextual overlay across <em>all</em> your processed transcripts simultaneously. It is your ultimate cross-reference engine.</p>
              <ul className="list-disc pl-5 space-y-2 text-on-surface-variant">
                <li>Ask questions like <em>"What did we decide about the Q4 marketing budget across all meetings?"</em></li>
                <li>The AI reasoning engine will scrape through every uploaded document you own and synthesize a single, concise answer.</li>
                <li>You can add or remove specific transcripts from the active AI context window using the tag pills above the chat box to narrow down the agent's focus.</li>
              </ul>
            </div>
          }
        />
      </div>

      <div className="mt-12 p-8 bg-surface-container-high rounded-3xl text-center space-y-4">
        <HelpCircle className="w-10 h-10 text-primary mx-auto opacity-50" />
        <h3 className="text-xl font-bold text-primary font-headline">Need further assistance?</h3>
        <p className="text-on-surface-variant">Reach out to your system administrator or file a ticket in your internal tracking portal.</p>
      </div>
    </div>
  );
};

const DocSection = ({ icon, num, title, content }: { icon: React.ReactNode, num: string, title: string, content: React.ReactNode }) => (
  <motion.div 
    initial={{ opacity: 0, y: 10 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    className="bg-white p-8 rounded-3xl shadow-sm border border-outline-variant/10 flex gap-6 group hover:shadow-md transition-shadow"
  >
    <div className="hidden md:flex flex-col items-center">
      <div className="text-4xl font-black text-surface-container-highest font-headline mt-2">{num}</div>
    </div>
    <div className="flex-1 space-y-4">
      <div className="flex items-center gap-3">
        <div className="p-2.5 bg-surface-container rounded-xl text-primary group-hover:bg-primary group-hover:text-white transition-colors">
          {React.cloneElement(icon as React.ReactElement, { className: "w-6 h-6" })}
        </div>
        <h2 className="text-2xl font-bold text-primary font-headline tracking-tight">{title}</h2>
      </div>
      <div className="text-on-surface-variant leading-relaxed">
        {content}
      </div>
    </div>
  </motion.div>
);
